M48
; DRILL file {KiCad (7.0.0)} date Sun Mar 26 02:59:32 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-26T02:59:32-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X200.346Y-32.197
X207.696Y-32.197
T2
X210.352Y-68.497
X211.368Y-63.417
X212.384Y-68.497
T0
M30
